# Generated by Django 5.0.2 on 2024-02-22 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_menu_menucategory_delete_menuitems_menu_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('contact_no', models.CharField(default='', max_length=300, verbose_name='Phone Number')),
                ('time', models.TimeField()),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('time_log', models.TimeField(help_text='Enter exact time')),
            ],
        ),
    ]
