# Generated by Django 5.0.3 on 2024-03-29 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsheringData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('session', models.CharField(max_length=100)),
                ('minister', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=300)),
                ('no_of_male', models.PositiveIntegerField(blank=True, null=True)),
                ('no_of_female', models.PositiveIntegerField(blank=True, null=True)),
                ('no_of_boys', models.PositiveIntegerField(blank=True, null=True)),
                ('no_of_girls', models.PositiveIntegerField(blank=True, null=True)),
                ('no_of_ymale', models.PositiveIntegerField(blank=True, null=True)),
                ('no_of_yfemale', models.PositiveIntegerField(blank=True, null=True)),
                ('no_of_yboys', models.PositiveIntegerField(blank=True, null=True)),
                ('no_of_ygirls', models.PositiveIntegerField(blank=True, null=True)),
                ('no_of_cmale', models.PositiveIntegerField(blank=True, null=True)),
                ('no_of_cfemale', models.PositiveIntegerField(blank=True, null=True)),
                ('no_of_cboys', models.PositiveIntegerField(blank=True, null=True)),
                ('no_of_cgirls', models.PositiveIntegerField(blank=True, null=True)),
                ('no_of_tmale', models.PositiveIntegerField(blank=True, null=True)),
                ('no_of_tfemale', models.PositiveIntegerField(blank=True, null=True)),
                ('no_of_tboys', models.PositiveIntegerField(blank=True, null=True)),
                ('no_of_tgirls', models.PositiveIntegerField(blank=True, null=True)),
                ('instagram', models.PositiveIntegerField(blank=True, null=True)),
                ('youtube', models.PositiveIntegerField(blank=True, null=True)),
                ('mixlr', models.PositiveIntegerField(blank=True, null=True)),
                ('facebook', models.PositiveIntegerField(blank=True, null=True)),
                ('website', models.PositiveIntegerField(blank=True, null=True)),
                ('offering_main', models.FloatField(blank=True, null=True)),
                ('tithe', models.FloatField(blank=True, null=True)),
                ('seed', models.FloatField(blank=True, null=True)),
                ('vow', models.FloatField(blank=True, null=True)),
                ('firstfruit', models.FloatField(blank=True, null=True)),
                ('cheque', models.FloatField(blank=True, null=True)),
                ('pos', models.FloatField(blank=True, null=True)),
                ('offering_children', models.FloatField(blank=True, null=True)),
                ('offering_teenagers', models.FloatField(blank=True, null=True)),
                ('foreign_currency', models.CharField(max_length=300)),
            ],
        ),
    ]
