[[redirects]]
from = "/*"
to = "/home.html"
status = 200

[build]
  functions = "/"

[dev]
  command = "python3 manage.py runserver"
 
  port = 8888  # Port for Netlify Dev's local server
  targetPort = 8000  # Port your own dev server runs on (e.g., Django's dev server)
  autoLaunch = true



[[edge_functions]]
function = "transform-response"
path = "/test"