[[redirects]]
from = "/*"
to = "/home.html"
status = 200

[build]
  publish = "dist" # The directory of your static files, adjust as needed

[dev]
  command = "python manage.py runserver"
  publish = "dist"  # Adjust based on where your static files are located
  port = 8888  # Port for Netlify Dev's local server
  targetPort = 8000  # Port your own dev server runs on (e.g., Django's dev server)
  autoLaunch = true

